version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_api
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Teste@123
      POSTGRES_DB: api_gateway_db
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: api_gateway
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/api_gateway_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Teste@123
    networks:
      - default

volumes:
  pgdata:
